# CI de nível 01, 02 e 03

name: 'Execução manual, agendada e push'

on:
  # disparo manual
  workflow_dispatch:

   #crononograma de execução
  # 1º - minuto, 2º - hora,  3º- dia do mês, 4º - mês, 5º - dia da semana
  schedule:
    - cron: '0 */6 * * *' # a cada 6 horas, ou seja, 4 vezes ao dia
  
  # disparo por push
  push:
    branches:
      - main
      
jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      - name: Verificar máquina
        run: hostname

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      # instalação das dependências
      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm run test:ci

      # upload do relatório de testes
      - name: Relatório de Testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: relatorio-mochawesome
          path: mochawesome-report/